//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ghostly.DAL.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deliverability
    {
        public System.Guid DeliverabilityId { get; set; }
        public Nullable<System.Guid> SupplierId { get; set; }
        public Nullable<System.Guid> CommercialIngredientId { get; set; }
        public Nullable<decimal> ProcurementTimeHours { get; set; }
        public Nullable<decimal> ProcurementTimeDays { get; set; }
        public Nullable<decimal> ProcurementTimeMonths { get; set; }
        public Nullable<decimal> MOQ { get; set; }
        public System.DateTime date_creation { get; set; }
        public Nullable<System.Guid> created_by { get; set; }
        public Nullable<System.Guid> modified_by { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
    
        public virtual CommercialIngredient CommercialIngredient { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
