//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ghostly.DAL.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class fdc_branded_food
    {
        public System.Guid id { get; set; }
        public double fdc_id { get; set; }
        public string brand_owner { get; set; }
        public Nullable<double> gtin_upc { get; set; }
        public string ingredients { get; set; }
        public Nullable<double> serving_size { get; set; }
        public string serving_size_unit { get; set; }
        public string household_serving_fulltext { get; set; }
        public string branded_food_category { get; set; }
        public string data_source { get; set; }
        public Nullable<System.DateTime> modified_date { get; set; }
        public Nullable<System.DateTime> available_date { get; set; }
        public string market_country { get; set; }
        public string discontinued_date { get; set; }
    
        public virtual fdc_food fdc_food { get; set; }
    }
}
