//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ghostly.DAL.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingredient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ingredient()
        {
            this.Conversions = new HashSet<Conversion>();
            this.StartStocks = new HashSet<StartStock>();
            this.StockDailySalesIngredients = new HashSet<StockDailySalesIngredient>();
            this.PriceCostVariations = new HashSet<PriceCostVariation>();
            this.StockUnespectedVariations = new HashSet<StockUnespectedVariation>();
        }
    
        public System.Guid IngredientId { get; set; }
        public string Name { get; set; }
        public string Category { get; set; }
        public string Type { get; set; }
        public Nullable<System.Guid> OperatorId { get; set; }
        public Nullable<System.Guid> OperatorLocationId { get; set; }
        public Nullable<System.Guid> CommercialIngredientId { get; set; }
        public Nullable<decimal> ProductionTimeHours { get; set; }
        public Nullable<decimal> ProductionTimeDays { get; set; }
        public Nullable<decimal> ProductionTimeMonths { get; set; }
        public Nullable<decimal> PerishabilityIndexHours { get; set; }
        public Nullable<decimal> PerishabilityIndexDays { get; set; }
        public string PerishabilityIndexMonths { get; set; }
        public Nullable<decimal> StorageCapacityInLiquid { get; set; }
        public Nullable<decimal> StorageCapacityInVolume { get; set; }
        public Nullable<decimal> StorageUsedCapacityLiquid { get; set; }
        public Nullable<decimal> StorageUsedCapacityVolume { get; set; }
        public Nullable<decimal> CurrentPrice { get; set; }
        public Nullable<decimal> LastCost { get; set; }
        public Nullable<System.DateTime> date_creation { get; set; }
        public Nullable<System.Guid> created_by { get; set; }
        public Nullable<System.Guid> modified_by { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
    
        public virtual CommercialIngredient CommercialIngredient { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Conversion> Conversions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StartStock> StartStocks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockDailySalesIngredient> StockDailySalesIngredients { get; set; }
        public virtual Operators_Locations Operators_Locations { get; set; }
        public virtual Operator Operator { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PriceCostVariation> PriceCostVariations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockUnespectedVariation> StockUnespectedVariations { get; set; }
    }
}
