//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ghostly.DAL.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class norm_Brands
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public norm_Brands()
        {
            this.CommercialIngredients = new HashSet<CommercialIngredient>();
        }
    
        public int BrandId { get; set; }
        public string BrandName { get; set; }
        public byte[] BrandLogo { get; set; }
        public string BrandRegion { get; set; }
        public string BrandCountry { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommercialIngredient> CommercialIngredients { get; set; }
        public virtual norm_Countries norm_Countries { get; set; }
        public virtual norm_Regions norm_Regions { get; set; }
    }
}
