//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ghostly.DAL.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class norm_CountriesInRegions
    {
        public long CountryRegion { get; set; }
        public string CountryId { get; set; }
        public string RegionId { get; set; }
    
        public virtual norm_Countries norm_Countries { get; set; }
        public virtual norm_Regions norm_Regions { get; set; }
    }
}
