//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ghostly.DAL.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class POI_POR_reconciliation
    {
        public System.Guid ReconciliationRecordId { get; set; }
        public Nullable<System.Guid> POIid { get; set; }
        public Nullable<System.Guid> PORid { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<decimal> RequestedQuantity { get; set; }
        public Nullable<decimal> DeliveredQuantity { get; set; }
        public Nullable<decimal> BalanceQuantity { get; set; }
        public Nullable<bool> Completed { get; set; }
    
        public virtual PurchaseOrderInvoice PurchaseOrderInvoice { get; set; }
        public virtual PurchaseOrderRequest PurchaseOrderRequest { get; set; }
    }
}
