//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ghostly.DAL.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcessIngredient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProcessIngredient()
        {
            this.PriceCostVariations = new HashSet<PriceCostVariation>();
            this.StockUnespectedVariations = new HashSet<StockUnespectedVariation>();
        }
    
        public System.Guid ProcessIngredientId { get; set; }
        public Nullable<System.Guid> IngredientId { get; set; }
        public Nullable<System.Guid> RawIngredientId { get; set; }
        public Nullable<int> Variation { get; set; }
        public string VariationType { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public string UnitType { get; set; }
        public Nullable<System.Guid> CommercialIngredientId { get; set; }
        public Nullable<decimal> PerishabilityIndexHours { get; set; }
        public Nullable<decimal> PerishabilityIndexDays { get; set; }
        public Nullable<decimal> PerishabilityIndexMonths { get; set; }
        public Nullable<decimal> CurrentPrice { get; set; }
        public Nullable<decimal> LastCost { get; set; }
        public System.DateTime date_creation { get; set; }
        public Nullable<System.Guid> created_by { get; set; }
        public Nullable<System.Guid> modified_by { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
    
        public virtual norm_UnitTypes norm_UnitTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PriceCostVariation> PriceCostVariations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockUnespectedVariation> StockUnespectedVariations { get; set; }
    }
}
