//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ghostly.DAL.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class prof_OperatorGhostlyClassification
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public prof_OperatorGhostlyClassification()
        {
            this.Operators = new HashSet<Operator>();
            this.Operators_Locations = new HashSet<Operators_Locations>();
        }
    
        public int OperatorGhostlyClassificationId { get; set; }
        public string OperatorGhostlyClassificationDesc { get; set; }
        public string Location { get; set; }
        public string Ownership { get; set; }
        public Nullable<bool> Franchising { get; set; }
        public string Menu { get; set; }
        public Nullable<bool> VirtualBrands { get; set; }
        public Nullable<bool> VeryHighInventoryComplexity { get; set; }
        public Nullable<bool> HighInventoryComplexity { get; set; }
        public Nullable<bool> MediumInventoryComplexity { get; set; }
        public Nullable<bool> LowInventoryComplexity { get; set; }
        public Nullable<bool> Seasonal { get; set; }
        public Nullable<bool> Interchangeable { get; set; }
        public Nullable<bool> MinimumExchange { get; set; }
        public Nullable<bool> NoExchange { get; set; }
        public Nullable<bool> ComplexCookingProcess { get; set; }
        public Nullable<bool> SemiComplexCookingProcess { get; set; }
        public Nullable<bool> LowComplexCookingProcess { get; set; }
        public Nullable<bool> VeryHighVolumeProvisioning { get; set; }
        public Nullable<bool> HighVolumeProvisioning { get; set; }
        public Nullable<bool> MediumProvisioning { get; set; }
        public Nullable<bool> LowProvisioning { get; set; }
        public System.DateTime date_creation { get; set; }
        public Nullable<System.Guid> created_by { get; set; }
        public Nullable<System.Guid> modified_by { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Operator> Operators { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Operators_Locations> Operators_Locations { get; set; }
    }
}
