//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ghostly.DAL.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrderInvoice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PurchaseOrderInvoice()
        {
            this.POI_POR_reconciliation = new HashSet<POI_POR_reconciliation>();
            this.PriceCostVariations = new HashSet<PriceCostVariation>();
        }
    
        public System.Guid PurchaseOrderInvoiceId { get; set; }
        public Nullable<System.Guid> SupplierId { get; set; }
        public Nullable<System.Guid> SupplierLocation { get; set; }
        public Nullable<System.Guid> OperatorId { get; set; }
        public Nullable<System.Guid> OperatorLocationId { get; set; }
        public string InvoiceRef { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.Guid> CommercialIngredientId { get; set; }
        public Nullable<System.Guid> ConversionId { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> TotalCost { get; set; }
        public Nullable<System.Guid> PurchaseOrderRequestId { get; set; }
        public Nullable<System.DateTime> date_creation { get; set; }
        public Nullable<System.Guid> created_by { get; set; }
        public Nullable<System.Guid> modified_by { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
    
        public virtual CommercialIngredient CommercialIngredient { get; set; }
        public virtual Conversion Conversion { get; set; }
        public virtual Operator Operator { get; set; }
        public virtual Operators_Locations Operators_Locations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POI_POR_reconciliation> POI_POR_reconciliation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PriceCostVariation> PriceCostVariations { get; set; }
        public virtual PurchaseOrderRequest PurchaseOrderRequest { get; set; }
        public virtual Suppliers_Location Suppliers_Location { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
