//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ghostly.DAL.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sale()
        {
            this.SaleRecipeModifiers = new HashSet<SaleRecipeModifier>();
        }
    
        public System.Guid SaleId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.TimeSpan> Time { get; set; }
        public string TimeZone { get; set; }
        public string Category { get; set; }
        public Nullable<int> Qty { get; set; }
        public string SKU { get; set; }
        public Nullable<decimal> GrossSales { get; set; }
        public Nullable<decimal> DicscountPerc { get; set; }
        public Nullable<decimal> Discounts { get; set; }
        public Nullable<decimal> NetSales { get; set; }
        public Nullable<decimal> TaxPerc { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public string TransactionID { get; set; }
        public string PaymentID { get; set; }
        public string DeviceName { get; set; }
        public string Notes { get; set; }
        public string Details { get; set; }
        public string EventType { get; set; }
        public string DiningOption { get; set; }
        public string CustomerID { get; set; }
        public string CustomerName { get; set; }
        public string CustomerReferenceID { get; set; }
        public string Unit { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<System.Guid> RecipeId { get; set; }
        public Nullable<System.Guid> OperatorId { get; set; }
        public Nullable<System.Guid> OperatorLocationId { get; set; }
        public Nullable<int> DeliveryChannel { get; set; }
        public System.DateTime date_creation { get; set; }
        public Nullable<System.Guid> created_by { get; set; }
        public Nullable<System.Guid> modified_by { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
    
        public virtual DeliveryChannel DeliveryChannel1 { get; set; }
        public virtual Operator Operator { get; set; }
        public virtual Operators_Locations Operators_Locations { get; set; }
        public virtual Recipe Recipe { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SaleRecipeModifier> SaleRecipeModifiers { get; set; }
    }
}
