//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ghostly.DAL.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleRecipeModifier
    {
        public System.Guid SaleRecipeModifierId { get; set; }
        public System.Guid ModifierId { get; set; }
        public System.Guid SaleId { get; set; }
        public System.DateTime date_creation { get; set; }
        public Nullable<System.Guid> created_by { get; set; }
        public Nullable<System.Guid> modified_by { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
    
        public virtual Modifier Modifier { get; set; }
        public virtual Sale Sale { get; set; }
    }
}
