//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ghostly.DAL.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockUnespectedVariation
    {
        public System.Guid UnespectedVariationId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<System.Guid> IngredientId { get; set; }
        public Nullable<System.Guid> ProcessIngredient { get; set; }
        public Nullable<System.Guid> CommercialIngredient { get; set; }
        public string Reason { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public System.DateTime date_creation { get; set; }
        public Nullable<System.Guid> created_by { get; set; }
        public Nullable<System.Guid> modified_by { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
    
        public virtual CommercialIngredient CommercialIngredient1 { get; set; }
        public virtual Ingredient Ingredient { get; set; }
        public virtual ProcessIngredient ProcessIngredient1 { get; set; }
    }
}
