//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ghostly.DAL.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Supplier()
        {
            this.aspnet_Users = new HashSet<aspnet_Users>();
            this.PurchaseOrderInvoices = new HashSet<PurchaseOrderInvoice>();
            this.PurchaseOrderRequests = new HashSet<PurchaseOrderRequest>();
            this.PurchaseOrderSuggestions = new HashSet<PurchaseOrderSuggestion>();
            this.PurchaseOrderSuggestionAlternatives = new HashSet<PurchaseOrderSuggestionAlternative>();
            this.Suppliers_Location = new HashSet<Suppliers_Location>();
        }
    
        public System.Guid SupplierId { get; set; }
        public string SupplierNameFirm { get; set; }
        public string SupplierVATid { get; set; }
        public string SupplierMainContact { get; set; }
        public string SupplierEmail { get; set; }
        public string SupplierTelephone { get; set; }
        public string SupplierCity { get; set; }
        public string SupplierAddressLine1 { get; set; }
        public string SupplierAddressLine2 { get; set; }
        public string SupplierCountry { get; set; }
        public string SupplierStateOrProvince { get; set; }
        public string SupplierRegion { get; set; }
        public Nullable<int> SupplierCategory { get; set; }
        public Nullable<int> SupplierSubCategory { get; set; }
        public Nullable<int> SupplierGhostlyClassification { get; set; }
        public Nullable<System.DateTime> date_creation { get; set; }
        public Nullable<System.Guid> created_by { get; set; }
        public Nullable<System.Guid> modified_by { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<aspnet_Users> aspnet_Users { get; set; }
        public virtual norm_Regions norm_Regions { get; set; }
        public virtual norm_SupplierCategories norm_SupplierCategories { get; set; }
        public virtual norm_SupplierSubCategories norm_SupplierSubCategories { get; set; }
        public virtual prof_SupplierGhostlyClassification prof_SupplierGhostlyClassification { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseOrderInvoice> PurchaseOrderInvoices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseOrderRequest> PurchaseOrderRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseOrderSuggestion> PurchaseOrderSuggestions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseOrderSuggestionAlternative> PurchaseOrderSuggestionAlternatives { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Suppliers_Location> Suppliers_Location { get; set; }
    }
}
