//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ghostly.DAL.SQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UniversalIngredient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UniversalIngredient()
        {
            this.CommercialIngredients = new HashSet<CommercialIngredient>();
            this.IngredientsForStandardRecipes = new HashSet<IngredientsForStandardRecipe>();
        }
    
        public System.Guid UniversalIngredientId { get; set; }
        public string Name { get; set; }
        public string Category { get; set; }
        public string Type { get; set; }
        public Nullable<decimal> PerishabilityIndexHours { get; set; }
        public Nullable<decimal> PerishabilityIndexDays { get; set; }
        public Nullable<decimal> PerishabilityIndexMonths { get; set; }
        public Nullable<bool> PerishabilityIsMandatory { get; set; }
        public System.DateTime date_creation { get; set; }
        public Nullable<System.Guid> created_by { get; set; }
        public Nullable<System.Guid> modified_by { get; set; }
        public Nullable<System.DateTime> date_modified { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommercialIngredient> CommercialIngredients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IngredientsForStandardRecipe> IngredientsForStandardRecipes { get; set; }
    }
}
